services:
  web:
    build: ./django_service
    entrypoint: /app/entrypoint.sh
    env_file:
      - ./.env
    volumes:
      - ./django_service/:/app/
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      - db

  go:
    build:
      context: ./go_service
      dockerfile: Dockerfile
    entrypoint: /app/entrypoint.sh
    ports:
      - "8080:8080"
    volumes:
      - ./go_service:/app
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  db:
    image: postgis/postgis:15-3.3
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always

#    TODO add redis for cache

  tbot:
    build: ./tbot
    entrypoint: python bot.py
    volumes:
      - ./tbot/:/app/
    env_file:
      - .env
    restart: always


volumes:
  postgres_volume: