
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    #image: postgres:12.0-alpine
    image: postgis/postgis:15-3.3
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always

volumes:
  postgres_volume: