
services:
  web:
    build:
      context: ./django_service
    command: python code/manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  go_service:
    build:
      context: ./go_service
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  db:
    #image: postgres:12.0-alpine
    image: postgis/postgis:15-3.3
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always

volumes:
  postgres_volume: